#pipeline {
 #   agent any
#
 #   tools {
  #      nodejs "node-lts"
   # }

   # stages {
#
 #       stage('Clone') {
  #          steps {
   #             git branch: 'main',
    #            url: 'https://github.com/bufferizer25/ERP'
     #       }
      #  }
#       stage('Install Dependencies') {
 #           steps {
  #              sh 'npm install'
   #         }
    #
     #   stage('Run Tests') {
      #      steps {
       #         sh 'npm test -- --watchAll=false'
        #    }
        #}

        #stage('Build React App') {
         #   steps {
          #      sh 'npm run build'
           # }
        #}

        #stage('Archive Build Artifacts') {
         #   steps {
          #      archiveArtifacts artifacts: 'build/**', fingerprint: true
           # }
        #}
    #}
#}
